server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi
          uri: http://user-cmd-api:8081/api/v1/user
          predicates:
            - Path=/api/v1/user
        - id: userCmdApi-star
          uri: http://user-cmd-api:8081/api/v1/user/**
          predicates:
            - Path=/api/v1/user/**
        - id: userQueryApi
          uri: http://user-query-api:8082/api/v1/user-search
          predicates:
            - Path=/api/v1/user-search
        - id: userQueryApi-star
          uri: http://user-query-api:8082/api/v1/user-search/**
          predicates:
            - Path=/api/v1/user-search/**
        - id: bankAccCmdApi-OpenAccount
          uri: http://bankacc-cmd-api:9091/api/v1/openBankAccount
          predicates:
            - Path=/api/v1/openBankAccount
        - id: bankAccCmdApi-DepositFunds
          uri: http://bankacc-cmd-api:9091/api/v1/depositFunds/**
          predicates:
            - Path=/api/v1/depositFunds/**
        - id: bankAccCmdApi-WithdrawFunds
          uri: http://bankacc-cmd-api:9091/api/v1/withdrawFunds/**
          predicates:
            - Path=/api/v1/withdrawFunds/**
        - id: bankAccCmdApi-CloseAccount
          uri: http://bankacc-cmd-api:9091/api/v1/closeBankAccount/**
          predicates:
            - Path=/api/v1/closeBankAccount/**
        - id: bankAccQueryApi
          uri: http://bankacc-query-api:9092/api/v1/bankAccountLookup/**
          predicates:
            - Path=/api/v1/bankAccountLookup/**

