#apiVersion: "v1"
#kind: "Namespace"
#metadata:
#  name: "shopping"
#---
#apiVersion: akka.lightbend.com/v1
#kind: AkkaMicroservice
#metadata:
#  name: shopping-cart-service
#  namespace: "shopping"
#spec:
#  replicas: 1
#  image: jhonderson/shopping-cart-service:20210324-174427-d99efad
#  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
#  resources:
#    limits:
#      memory: "2Gi"
#    requests:
#      memory: "2Gi"
#      cpu: "1"

apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "shopping"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
  namespace: "shopping"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-service
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
        - name: shopping-cart-service
          image: jhonderson/shopping-cart-service:latest
          ports:
            - containerPort: 8101
          env:
            - name: APP_CONFIG
              value: "local1.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service-entrypoint
  namespace: "shopping"
spec:
  selector:
    app: shopping-cart-service
  ports:
    - protocol: TCP
      port: 8101
#---
#apiVersion: "v1"
#kind: "Namespace"
#metadata:
#  name: "shopping"
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: "shopping"
#  name: my-nginx
#spec:
#  selector:
#    matchLabels:
#      run: my-nginx
#  replicas: 2
#  template:
#    metadata:
#      labels:
#        run: my-nginx
#    spec:
#      containers:
#        - name: my-nginx
#          image: nginx
#          ports:
#            - containerPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: "shopping"
#  name: my-nginx
#  labels:
#    run: my-nginx
#spec:
#  ports:
#    - port: 80
#      protocol: TCP
#  selector:
#    run: my-nginx